name = "Main Quest Mob"
author = "Noxedwin"
version = "1.00"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e554defc0c35fc3f687548948c5578370675610567ddf1d0d38192208d01ecdb"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
