name = "Main Quest Mob"
author = "Noxedwin"
version = "1.00"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e81fbb9704005316b7050662caa25fed168b126a341a07b4e9bf35ba684a581"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
